# Change these first
owner: async0x42 # Your GitHub username
repo: epic-upptime # Your Github repository name

# Add your sites here
sites:
  #- name: Confluence
  #  url: https://confluence.ongarde.net/
  - name: GitLab
    url: https://git.ongarde.net/
  - name: Snap Survey (External)
    url: https://survey-sondage.forces.gc.ca/snapwebhost/
  - name: Learning Portal
    url: https://lp-pa.forces.gc.ca/portal/
  - name: H5P
    url: https://h5p.ongarde.net/
  - name: CAF-ACE
    url: https://caface-rfacace.forces.gc.ca
#  - name: CAF-ACE (Staging)
#    url: https://caface.ongarde.net
  - name: DGCB (Staging)
    url: https://dgcb.ongarde.net
  - name: DGCB Knowledge
    url: https://v10.ongarde.net
  - name: DTC (Staging)
    url: https://dtc.ongarde.net
  - name: Equella
    url: https://equella.ongarde.net
  - name: Forces.ca
    url: https://forces.ca
  - name: Forces.ca (Staging)
    url: https://forces.ongarde.net
  - name: Snipe-IT
    url: https://snipe.ongarde.net
  - name: FMOST-Outcan
    url: https://outcan.ongarde.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /epic-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EPIC Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Server status intro message...
  navbar:
    - title: Status
      href: /epic-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
